import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { AdminLayout } from '../../components/layouts/AdminLayout';
import { PageHeader } from '../../components/ui/AdminComponents';
import { User, Building2, Lock, Bell } from 'lucide-react';
export default function Settings() {
    const [activeTab, setActiveTab] = useState('profile');
    const tabs = [
        { id: 'profile', label: 'Perfil', icon: User },
        { id: 'organization', label: 'Organização', icon: Building2 },
        { id: 'security', label: 'Segurança', icon: Lock },
        { id: 'notifications', label: 'Notificações', icon: Bell },
    ];
    return (_jsxs(AdminLayout, { children: [_jsx(PageHeader, { title: "Configura\u00E7\u00F5es", description: "Gerenciar prefer\u00EAncias e configura\u00E7\u00F5es" }), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-4 gap-6", children: [_jsx("div", { className: "lg:col-span-1", children: _jsx("div", { className: "bg-white rounded-lg border border-gray-200 p-2", children: tabs.map(tab => {
                                const Icon = tab.icon;
                                return (_jsxs("button", { onClick: () => setActiveTab(tab.id), className: `w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors ${activeTab === tab.id
                                        ? 'bg-blue-50 text-blue-600'
                                        : 'text-gray-700 hover:bg-gray-50'}`, children: [_jsx(Icon, { className: "w-5 h-5" }), tab.label] }, tab.id));
                            }) }) }), _jsx("div", { className: "lg:col-span-3", children: _jsxs("div", { className: "bg-white rounded-lg border border-gray-200 p-6", children: [activeTab === 'profile' && (_jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-lg font-semibold", children: "Informa\u00E7\u00F5es Pessoais" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Nome" }), _jsx("input", { type: "text", defaultValue: "Denis May", className: "w-full px-4 py-2 border border-gray-300 rounded-lg" })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Email" }), _jsx("input", { type: "email", defaultValue: "denis@example.com", className: "w-full px-4 py-2 border border-gray-300 rounded-lg" })] })] }), _jsx("button", { className: "px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "Salvar Altera\u00E7\u00F5es" })] })), activeTab === 'organization' && (_jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-lg font-semibold", children: "Configura\u00E7\u00F5es da Organiza\u00E7\u00E3o" }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Nome da Organiza\u00E7\u00E3o" }), _jsx("input", { type: "text", defaultValue: "Minha Empresa", className: "w-full px-4 py-2 border border-gray-300 rounded-lg" })] }), _jsx("button", { className: "px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "Salvar" })] })), activeTab === 'security' && (_jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-lg font-semibold", children: "Seguran\u00E7a" }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-2", children: "Alterar Senha" }), _jsx("input", { type: "password", placeholder: "Nova senha", className: "w-full px-4 py-2 border border-gray-300 rounded-lg" })] }), _jsx("button", { className: "px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700", children: "Atualizar Senha" })] })), activeTab === 'notifications' && (_jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-lg font-semibold", children: "Prefer\u00EAncias de Notifica\u00E7\u00F5es" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("label", { className: "flex items-center gap-3", children: [_jsx("input", { type: "checkbox", defaultChecked: true, className: "rounded" }), _jsx("span", { className: "text-gray-700", children: "Email notifications" })] }), _jsxs("label", { className: "flex items-center gap-3", children: [_jsx("input", { type: "checkbox", defaultChecked: true, className: "rounded" }), _jsx("span", { className: "text-gray-700", children: "Push notifications" })] })] })] }))] }) })] })] }));
}
