import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function StatCard({ title, value, icon: Icon, trend, className = '' }) {
    return (_jsx("div", { className: `bg-white rounded-lg border border-gray-200 p-6 ${className}`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex-1", children: [_jsx("p", { className: "text-sm font-medium text-gray-600", children: title }), _jsx("p", { className: "mt-2 text-3xl font-bold text-gray-900", children: value }), trend && (_jsxs("div", { className: "mt-2 flex items-center gap-1", children: [_jsxs("span", { className: `text-sm font-medium ${trend.isPositive ? 'text-green-600' : 'text-red-600'}`, children: [trend.isPositive ? '+' : '', trend.value, "%"] }), _jsx("span", { className: "text-sm text-gray-500", children: "vs. \u00FAltimo m\u00EAs" })] }))] }), _jsx("div", { className: "flex-shrink-0", children: _jsx("div", { className: "w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center", children: _jsx(Icon, { className: "w-6 h-6 text-blue-600" }) }) })] }) }));
}
export function DataTable({ columns, data, onRowClick }) {
    return (_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full divide-y divide-gray-200", children: [_jsx("thead", { className: "bg-gray-50", children: _jsx("tr", { children: columns.map((column) => (_jsx("th", { className: "px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider", children: column.label }, column.key))) }) }), _jsx("tbody", { className: "bg-white divide-y divide-gray-200", children: data.map((row, index) => (_jsx("tr", { onClick: () => onRowClick?.(row), className: onRowClick ? 'cursor-pointer hover:bg-gray-50' : '', children: columns.map((column) => (_jsx("td", { className: "px-6 py-4 whitespace-nowrap text-sm text-gray-900", children: column.render ? column.render(row[column.key], row) : row[column.key] }, column.key))) }, index))) })] }) }));
}
export function SearchBar({ placeholder = 'Buscar...', onSearch, className = '' }) {
    return (_jsxs("div", { className: `relative ${className}`, children: [_jsx("input", { type: "text", placeholder: placeholder, onChange: (e) => onSearch(e.target.value), className: "w-full px-4 py-2 pl-10 pr-4 text-gray-900 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent" }), _jsx("svg", { className: "absolute left-3 top-2.5 h-5 w-5 text-gray-400", fill: "none", stroke: "currentColor", viewBox: "0 0 24 24", children: _jsx("path", { strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: 2, d: "M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" }) })] }));
}
export function PageHeader({ title, description, action }) {
    return (_jsx("div", { className: "mb-8", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-3xl font-bold text-gray-900", children: title }), description && (_jsx("p", { className: "mt-2 text-sm text-gray-600", children: description }))] }), action && (_jsx("div", { children: action }))] }) }));
}
